[build]
  command = "npm run build:netlify"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Redirect rules for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for better security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Custom domain redirects
[[redirects]]
  from = "https://redbee-expo.netlify.app/*"
  to = "https://redbeeapp.com/:splat"
  status = 301
  force = true

# Auth callback handling
[[redirects]]
  from = "/auth/confirm"
  to = "/auth/confirm-password"
  status = 302
  query = {token_hash = ":token_hash", type = ":type"}

# API proxy for Supabase (optional)
[[redirects]]
  from = "/api/*"
  to = "https://hecpxuoxynuamcmzwulm.supabase.co/:splat"
  status = 200
  headers = {Authorization = "Bearer sb_publishable_lCB9zfPj0tOboOr0V0a3xQ_AeN6D3Uu"}